/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApresentacaoAcessaiRouteImport } from './routes/apresentacao-acessai'
import { Route as IndexRouteImport } from './routes/index'

const ApresentacaoAcessaiRoute = ApresentacaoAcessaiRouteImport.update({
  id: '/apresentacao-acessai',
  path: '/apresentacao-acessai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentacao-acessai': typeof ApresentacaoAcessaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentacao-acessai': typeof ApresentacaoAcessaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apresentacao-acessai': typeof ApresentacaoAcessaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apresentacao-acessai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apresentacao-acessai'
  id: '__root__' | '/' | '/apresentacao-acessai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApresentacaoAcessaiRoute: typeof ApresentacaoAcessaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/apresentacao-acessai': {
      id: '/apresentacao-acessai'
      path: '/apresentacao-acessai'
      fullPath: '/apresentacao-acessai'
      preLoaderRoute: typeof ApresentacaoAcessaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApresentacaoAcessaiRoute: ApresentacaoAcessaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
